package cripel.jobway.model;
// Generated Feb 25, 2022, 8:26:41 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Civilstatus generated by hbm2java
 */
@Entity
@Table(name = "civilstatus", catalog = "jobway")
public class CivilStatus implements java.io.Serializable {

	private Integer idCivilStatus;
	private String civilStatusName;
	private boolean isDelete;
	private Set<Person> persons = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCivilStatus", unique = true, nullable = false)
	public Integer getIdCivilStatus() {
		return this.idCivilStatus;
	}

	public void setIdCivilStatus(Integer idCivilStatus) {
		this.idCivilStatus = idCivilStatus;
	}

	@Column(name = "civilStatusName", nullable = false, length = 50)
	public String getCivilStatusName() {
		return this.civilStatusName;
	}

	public void setCivilStatusName(String civilStatusName) {
		this.civilStatusName = civilStatusName;
	}

	@Column(name = "isDelete", nullable = false)
	public boolean isDelete() {
		return isDelete;
	}

	public void setDelete(boolean isDelete) {
		this.isDelete = isDelete;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "civilstatus")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

	@Override
	public String toString() {
		return this.civilStatusName;
	}

}
