package cripel.jobway.model;
// Generated Feb 25, 2022, 8:26:41 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Difficulty generated by hbm2java
 */
@Entity
@Table(name = "disability", catalog = "jobway")
public class Disability implements java.io.Serializable {

	private Integer idDisability;
	private boolean disReco;
	private String disOther;
	private Set<Person> persons = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idDisability", unique = true, nullable = false)
	public Integer getIdDisability() {
		return this.idDisability;
	}

	public void setIdDisability(Integer idDisability) {
		this.idDisability = idDisability;
	}

	@Column(name = "disReco", nullable = false)
	public boolean isDisReco() {
		return this.disReco;
	}

	public void setDisReco(boolean disReco) {
		this.disReco = disReco;
	}

	@Column(name = "disOther", nullable = false, length = 50)
	public String getDisOther() {
		return this.disOther;
	}

	public void setDisOther(String disOther) {
		this.disOther = disOther;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "disability")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

}
