package cripel.jobway.model;
// Generated Feb 25, 2022, 8:26:41 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "jobway")
public class Employee implements java.io.Serializable {

	private Integer idEmployee;
	private String empPseudo;
	private String empName;
	private String empFirstName;
	private boolean empIsDelete;
	private Set<User> users = new HashSet<>(0);
	private Set<Person> persons = new HashSet<>(0);
	private Set<Event> events = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idEmployee", unique = true, nullable = false)
	public Integer getIdEmployee() {
		return this.idEmployee;
	}

	public void setIdEmployee(Integer idEmployee) {
		this.idEmployee = idEmployee;
	}

	@Column(name = "empPseudo", nullable = false, length = 50)
	public String getEmpPseudo() {
		return this.empPseudo;
	}

	public void setEmpPseudo(String empPseudo) {
		this.empPseudo = empPseudo;
	}

	@Column(name = "empName", nullable = true, length = 50)
	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Column(name = "empFirstName", nullable = true, length = 50)
	public String getEmpFirstName() {
		return this.empFirstName;
	}

	public void setEmpFirstName(String empFirstName) {
		this.empFirstName = empFirstName;
	}

	@Column(name = "empIsDelete", nullable = false)
	public boolean isEmpIsDelete() {
		return this.empIsDelete;
	}

	public void setEmpIsDelete(boolean empIsDelete) {
		this.empIsDelete = empIsDelete;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<Person> getPersons() {
		return persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

	@Override
	public String toString() {
		return this.empPseudo;
	}

	@Override
	public int hashCode() {
		return Objects.hash(idEmployee);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if ((obj == null) || (getClass() != obj.getClass()))
			return false;
		Employee other = (Employee) obj;
		return Objects.equals(idEmployee, other.idEmployee);
	}

}
