package cripel.jobway.model;
// Generated Feb 25, 2022, 8:26:41 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Formation generated by hbm2java
 */
@Entity
@Table(name = "formation", catalog = "jobway")
public class Formation implements java.io.Serializable {

	private Integer idFormation;
	private FormationType formationtype;
	private String formationName;
	private Boolean equIntro;
	private Boolean equObt;
	private boolean foreignFormation;
	private Boolean foreignHUE;
	private Date formationDate;
	private Set<Person> persons = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFormation", unique = true, nullable = false)
	public Integer getIdFormation() {
		return this.idFormation;
	}

	public void setIdFormation(Integer idFormation) {
		this.idFormation = idFormation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFormationType", nullable = false)
	public FormationType getFormationtype() {
		return this.formationtype;
	}

	public void setFormationtype(FormationType formationtype) {
		this.formationtype = formationtype;
	}

	@Column(name = "formationName", nullable = false, length = 50)
	public String getFormationName() {
		return this.formationName;
	}

	public void setFormationName(String formationName) {
		this.formationName = formationName;
	}

	@Column(name = "equIntro", nullable = true)
	public Boolean isEquIntro() {
		return this.equIntro;
	}

	public void setEquIntro(Boolean equIntro) {
		this.equIntro = equIntro;
	}

	@Column(name = "equObt", nullable = true)
	public Boolean isEquObt() {
		return this.equObt;
	}

	public void setEquObt(Boolean equObt) {
		this.equObt = equObt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "formationDate", nullable = true, length = 10)
	public Date getFormationDate() {
		return this.formationDate;
	}

	public void setFormationDate(Date formationDate) {
		this.formationDate = formationDate;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "formations", cascade = CascadeType.ALL)
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

	@Column(name = "foreignFormation", nullable = false)
	public boolean isForeignFormation() {
		return foreignFormation;
	}

	public void setForeignFormation(boolean foreignFormation) {
		this.foreignFormation = foreignFormation;
	}

	@Column(name = "foreignHUE", nullable = true)
	public Boolean isForeignHUE() {
		return foreignHUE;
	}

	public void setForeignHUE(Boolean foreignHUE) {
		this.foreignHUE = foreignHUE;
	}

	@Override
	public String toString() {
		return this.formationName;
	}

}
