package cripel.jobway.model;
// Generated Feb 25, 2022, 8:26:41 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Languagetest generated by hbm2java
 */
@Entity
@Table(name = "frenchtest", catalog = "jobway")
public class FrenchTest implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFrenchTest", unique = true, nullable = false)
	private Integer idFrenchTest;
	@Column(name = "frenchTestName", nullable = true, length = 50)
	private String frenchTestName;
	@Column(name = "isDelete", nullable = false)
	private boolean isDelete;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "frenchTest")
	private Set<Person> persons = new HashSet<>(0);

	public Integer getIdFrenchTest() {
		return idFrenchTest;
	}

	public void setIdFrenchTest(Integer idFrenchTest) {
		this.idFrenchTest = idFrenchTest;
	}

	public String getFrenchTestName() {
		return frenchTestName;
	}

	public void setFrenchTestName(String frenchTestName) {
		this.frenchTestName = frenchTestName;
	}

	public boolean isDelete() {
		return isDelete;
	}

	public void setDelete(boolean isDelete) {
		this.isDelete = isDelete;
	}

	public Set<Person> getPersons() {
		return persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

	@Override
	public String toString() {
		return this.frenchTestName;
	}
}
