package cripel.jobway.model;
// Generated Feb 25, 2022, 8:26:41 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Household generated by hbm2java
 */
@Entity
@Table(name = "household", catalog = "jobway")
public class Household implements java.io.Serializable {

	private Integer idHousehold;
	private int householdNumberAdult;
	private int householdNumberChildren;
	private Boolean householdGuardNeeded;
	private Boolean householdIspNeeded;
	private String householdIspName;
	private Set<Person> persons = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idHousehold", unique = true, nullable = false)
	public Integer getIdHousehold() {
		return this.idHousehold;
	}

	public void setIdHousehold(Integer idHousehold) {
		this.idHousehold = idHousehold;
	}

	@Column(name = "householdNumberAdult", nullable = false)
	public int getHouseholdNumberAdult() {
		return this.householdNumberAdult;
	}

	public void setHouseholdNumberAdult(int householdNumberAdult) {
		this.householdNumberAdult = householdNumberAdult;
	}

	@Column(name = "householdNumberChildren", nullable = false)
	public int getHouseholdNumberChildren() {
		return this.householdNumberChildren;
	}

	public void setHouseholdNumberChildren(int householdNumberChildren) {
		this.householdNumberChildren = householdNumberChildren;
	}

	@Column(name = "householdGuardNeeded", nullable = true)
	public Boolean isHouseholdGuardNeeded() {
		return householdGuardNeeded;
	}

	public void setHouseholdGuardNeeded(Boolean householdGuardNeeded) {
		this.householdGuardNeeded = householdGuardNeeded;
	}

	@Column(name = "householdIspNeeded", nullable = true)
	public Boolean isHouseholdIspNeeded() {
		return householdIspNeeded;
	}

	public void setHouseholdIspNeeded(Boolean householdIspNeeded) {
		this.householdIspNeeded = householdIspNeeded;
	}

	@Column(name = "householdIspName", nullable = true)
	public String getHouseholdIspName() {
		return householdIspName;
	}

	public void setHouseholdIspName(String householdIspName) {
		this.householdIspName = householdIspName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "household")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

}
