package cripel.jobway.model;
// Generated Feb 25, 2022, 8:26:41 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Incometype generated by hbm2java
 */
@Entity
@Table(name = "incometype", catalog = "jobway")
public class IncomeType implements java.io.Serializable {

	private Integer idIncomeType;
	private String incomeTypeName;
	private boolean isDelete;
	private Set<Person> persons = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idIncomeType", unique = true, nullable = false)
	public Integer getIdIncomeType() {
		return this.idIncomeType;
	}

	public void setIdIncomeType(Integer idIncomeType) {
		this.idIncomeType = idIncomeType;
	}

	@Column(name = "incomeTypeName", nullable = false, length = 50)
	public String getIncomeTypeName() {
		return this.incomeTypeName;
	}

	public void setIncomeTypeName(String incomeTypeName) {
		this.incomeTypeName = incomeTypeName;
	}

	@Column(name = "isDelete", nullable = false)
	public boolean isDelete() {
		return isDelete;
	}

	public void setDelete(boolean isDelete) {
		this.isDelete = isDelete;
	}

	@ManyToMany(mappedBy = "incometypes")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

	@Override
	public String toString() {
		return this.incomeTypeName;
	}

	@Override
	public int hashCode() {
		return Objects.hash(idIncomeType);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if ((obj == null) || (getClass() != obj.getClass()))
			return false;
		IncomeType other = (IncomeType) obj;
		return Objects.equals(idIncomeType, other.idIncomeType);
	}

}
