package cripel.jobway.model;
// Generated Feb 25, 2022, 8:26:41 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Logs generated by hbm2java
 */
@Entity
@Table(name = "logs", catalog = "jobway")
public class Logs {

	private Integer idLog;
	private String logger;
	private String logMessage;
	private Date logDate;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idLog", unique = true, nullable = false)
	public Integer getIdLog() {
		return this.idLog;
	}

	public void setIdLog(Integer idLog) {
		this.idLog = idLog;
	}

	@Column(name = "logger", nullable = false, length = 50)
	public String getLogger() {
		return this.logger;
	}

	public void setLogger(String logger) {
		this.logger = logger;
	}

	@Column(name = "logMessage", nullable = false, length = 1000)
	public String getLogMessage() {
		return this.logMessage;
	}

	public void setLogMessage(String logMessage) {
		this.logMessage = logMessage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logDate", nullable = false, length = 19)
	public Date getLogDate() {
		return this.logDate;
	}

	public void setLogDate(Date logDate) {
		this.logDate = logDate;
	}

}
