package cripel.jobway.model;
// Generated Feb 25, 2022, 8:26:41 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AssociationOverride;
import javax.persistence.AssociationOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * PerSkill generated by hbm2java
 */
@Entity
@Table(name = "per_skill", catalog = "jobway")
@AssociationOverrides({ @AssociationOverride(name = "id.skill", joinColumns = @JoinColumn(name = "idSkill")),
		@AssociationOverride(name = "id.person", joinColumns = @JoinColumn(name = "idPerson")) })
public class PerSkill implements java.io.Serializable {

	private PerSkillId id = new PerSkillId();
	private String skillLvl;

	public PerSkill() {
	}

	@EmbeddedId
	public PerSkillId getId() {
		return this.id;
	}

	public void setId(PerSkillId id) {
		this.id = id;
	}

	@Transient
	public Person getPerson() {
		return getId().getPerson();
	}

	public void setPerson(Person person) {
		getId().setPerson(person);
	}

	@Transient
	public Skill getSkill() {
		return getId().getSkill();
	}

	public void setSkill(Skill skill) {
		getId().getSkill();
	}

	@Column(name = "skillLvl", nullable = false, length = 50)
	public String getSkillLvl() {
		return this.skillLvl;
	}

	public void setSkillLvl(String skillLvl) {
		this.skillLvl = skillLvl;
	}

}
