package cripel.jobway.model;
// Generated Feb 25, 2022, 8:26:41 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Postalcode generated by hbm2java
 */
@Entity
@Table(name = "postalcode", catalog = "jobway")
public class Postalcode implements java.io.Serializable {

	private Integer idPostalCode;
	private String postalCodeNumber;
	private boolean isDelete;
	private Set<City> cities = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPostalCode", unique = true, nullable = false)
	public Integer getIdPostalCode() {
		return this.idPostalCode;
	}

	public void setIdPostalCode(Integer idPostalCode) {
		this.idPostalCode = idPostalCode;
	}

	@Column(name = "postalCodeNumber", nullable = false, length = 50)
	public String getPostalCodeNumber() {
		return this.postalCodeNumber;
	}

	public void setPostalCodeNumber(String postalCodeNumber) {
		this.postalCodeNumber = postalCodeNumber;
	}

	@Column(name = "isDelete", nullable = false)
	public boolean isDelete() {
		return isDelete;
	}

	public void setDelete(boolean isDelete) {
		this.isDelete = isDelete;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "postalcode")
	public Set<City> getCities() {
		return this.cities;
	}

	public void setCities(Set<City> cities) {
		this.cities = cities;
	}

	@Override
	public String toString() {
		return this.postalCodeNumber;
	}
}
