package cripel.jobway.model;
// Generated Feb 25, 2022, 8:26:41 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Residencepermit generated by hbm2java
 */
@Entity
@Table(name = "residencepermit", catalog = "jobway", uniqueConstraints = @UniqueConstraint(columnNames = "idPerson"))
public class ResidencePermit {

	private Integer idResidencePermit;
	private Person person;
	private ResidencePermitType residencepermittype;
	private Date residencePermitIssueDate;
	private Date residencePermitValidityDate;
	private String residencePermitAnnex;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idResidencePermit", unique = true, nullable = false)
	public Integer getIdResidencePermit() {
		return this.idResidencePermit;
	}

	public void setIdResidencePermit(Integer idResidencePermit) {
		this.idResidencePermit = idResidencePermit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPerson", unique = true, nullable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idResidencePermitType", nullable = false)
	public ResidencePermitType getResidencepermittype() {
		return this.residencepermittype;
	}

	public void setResidencepermittype(ResidencePermitType residencepermittype) {
		this.residencepermittype = residencepermittype;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "residencePermitIssueDate", nullable = true, length = 10)
	public Date getResidencePermitIssueDate() {
		return this.residencePermitIssueDate;
	}

	public void setResidencePermitIssueDate(Date residencePermitIssueDate) {
		this.residencePermitIssueDate = residencePermitIssueDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "residencePermitValidityDate", nullable = true, length = 10)
	public Date getResidencePermitValidityDate() {
		return this.residencePermitValidityDate;
	}

	public void setResidencePermitValidityDate(Date residencePermitValidityDate) {
		this.residencePermitValidityDate = residencePermitValidityDate;
	}

	@Column(name = "residencePermitAnnex", length = 50)
	public String getResidencePermitAnnex() {
		return this.residencePermitAnnex;
	}

	public void setResidencePermitAnnex(String residencePermitAnnex) {
		this.residencePermitAnnex = residencePermitAnnex;
	}

}
