package cripel.jobway.model;
// Generated Feb 25, 2022, 8:26:41 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Situationterritory generated by hbm2java
 */
@Entity
@Table(name = "situationterritory", catalog = "jobway")
public class SituationTerritory {

	private Integer idSituationTerritory;
	private String situationTerritoryName;
	private boolean isDelete;
	private Set<Person> persons = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idSituationTerritory", unique = true, nullable = false)
	public Integer getIdSituationTerritory() {
		return this.idSituationTerritory;
	}

	public void setIdSituationTerritory(Integer idSituationTerritory) {
		this.idSituationTerritory = idSituationTerritory;
	}

	@Column(name = "situationTerritoryName", nullable = false, length = 50)
	public String getSituationTerritoryName() {
		return this.situationTerritoryName;
	}

	public void setSituationTerritoryName(String situationTerritoryName) {
		this.situationTerritoryName = situationTerritoryName;
	}

	@Column(name = "isDelete", nullable = false)
	public boolean isDelete() {
		return isDelete;
	}

	public void setDelete(boolean isDelete) {
		this.isDelete = isDelete;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "situationterritory")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

	@Override
	public String toString() {
		return this.getSituationTerritoryName();
	}
}
