package cripel.jobway.model;
// Generated Feb 25, 2022, 8:26:41 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SkilSectId generated by hbm2java
 */
@Embeddable
public class SkilSectId implements java.io.Serializable {

	private int idWorkSector;
	private int idSkill;

	public SkilSectId() {
	}

	public SkilSectId(int idWorkSector, int idSkill) {
		this.idWorkSector = idWorkSector;
		this.idSkill = idSkill;
	}

	@Column(name = "idWorkSector", nullable = false)
	public int getIdWorkSector() {
		return this.idWorkSector;
	}

	public void setIdWorkSector(int idWorkSector) {
		this.idWorkSector = idWorkSector;
	}

	@Column(name = "idSkill", nullable = false)
	public int getIdSkill() {
		return this.idSkill;
	}

	public void setIdSkill(int idSkill) {
		this.idSkill = idSkill;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null) || !(other instanceof SkilSectId))
			return false;
		SkilSectId castOther = (SkilSectId) other;

		return (this.getIdWorkSector() == castOther.getIdWorkSector()) && (this.getIdSkill() == castOther.getIdSkill());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdWorkSector();
		result = 37 * result + this.getIdSkill();
		return result;
	}

}
