package cripel.jobway.model;
// Generated Feb 25, 2022, 8:26:41 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Skill generated by hbm2java
 */
@Entity
@Table(name = "skill", catalog = "jobway")
public class Skill implements java.io.Serializable {

	private Integer idSkill;
	private Set<SkilSect> skilSects = new HashSet<>(0);
	private Set<PerSkill> perSkills = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idSkill", unique = true, nullable = false)
	public Integer getIdSkill() {
		return this.idSkill;
	}

	public void setIdSkill(Integer idSkill) {
		this.idSkill = idSkill;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "skill")
	public Set<SkilSect> getSkilSects() {
		return this.skilSects;
	}

	public void setSkilSects(Set<SkilSect> skilSects) {
		this.skilSects = skilSects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "id.skill")
	public Set<PerSkill> getPerSkills() {
		return this.perSkills;
	}

	public void setPerSkills(Set<PerSkill> perSkills) {
		this.perSkills = perSkills;
	}

}
