package cripel.jobway.model;
// Generated Feb 25, 2022, 8:26:41 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SkilSect generated by hbm2java
 */
@Entity
@Table(name = "skil_sect", catalog = "jobway")
public class SkilSect {

	private SkilSectId id;
	private Skill skill;
	private WorkSector worksector;
	private String skilLvl;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idWorkSector", column = @Column(name = "idWorkSector", nullable = false)),
			@AttributeOverride(name = "idSkill", column = @Column(name = "idSkill", nullable = false)) })
	public SkilSectId getId() {
		return this.id;
	}

	public void setId(SkilSectId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSkill", nullable = false, insertable = false, updatable = false)
	public Skill getSkill() {
		return this.skill;
	}

	public void setSkill(Skill skill) {
		this.skill = skill;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idWorkSector", nullable = false, insertable = false, updatable = false)
	public WorkSector getWorksector() {
		return this.worksector;
	}

	public void setWorksector(WorkSector worksector) {
		this.worksector = worksector;
	}

	@Column(name = "skilLvl", nullable = false, length = 50)
	public String getSkilLvl() {
		return this.skilLvl;
	}

	public void setSkilLvl(String skilLvl) {
		this.skilLvl = skilLvl;
	}

}
