package cripel.jobway.model;
// Generated Feb 25, 2022, 8:26:41 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Userlevel generated by hbm2java
 */
@Entity
@Table(name = "userlevel", catalog = "jobway")
public class UserLevel {

	private Integer idUserLevel;
	private String userLevelName;
	private Set<User> users = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUserLevel", unique = true, nullable = false)
	public Integer getIdUserLevel() {
		return this.idUserLevel;
	}

	public void setIdUserLevel(Integer idUserLevel) {
		this.idUserLevel = idUserLevel;
	}

	@Column(name = "userLevelName", nullable = false, length = 50)
	public String getUserLevelName() {
		return this.userLevelName;
	}

	public void setUserLevelName(String userLevelName) {
		this.userLevelName = userLevelName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userlevel")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@Override
	public String toString() {
		return this.userLevelName;
	}

}
