package cripel.jobway.model;
// Generated Feb 25, 2022, 8:26:41 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Workexperience generated by hbm2java
 */
@Entity
@Table(name = "workexperience", catalog = "jobway")
public class WorkExperience {

	private Integer idWorkExp;
	private Person person;
	private WorkExpType workExptype;
	private String workExpName;
	private int workExpDurationMonth;
	private Boolean workExpBelgium;
	private String workSector;
	private Set<WorkTask> worktasks = new HashSet<>(0);
	public StringProperty worktasksProperty;

	//To display the tasks in the FormG setUpTableView() columnTaches
	public StringProperty worktasksProperty()
	{
		StringBuilder s = new StringBuilder();

		worktasks.forEach(
				wt -> {

					System.out.println(wt.getWorkTaskDescription());

					s.append("+ ").append(wt.getWorkTaskDescription()).append("\n");

				});

		System.out.println(s);

		//YES
		StringProperty sp = new SimpleStringProperty(s.toString());

		return sp;

	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idWorkExp", unique = true, nullable = false)
	public Integer getIdWorkExp() {
		return this.idWorkExp;
	}

	public void setIdWorkExp(Integer idWorkExp) {
		this.idWorkExp = idWorkExp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPerson", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idWorkExpType", nullable = false)
	public WorkExpType getWorkexptype() {
		return this.workExptype;
	}

	public void setWorkexptype(WorkExpType workexptype) {
		this.workExptype = workexptype;
	}

	@Column(name = "workExpName", nullable = false, length = 100)
	public String getWorkExpName() {
		return this.workExpName;
	}

	public void setWorkExpName(String workExpName) {
		this.workExpName = workExpName;
	}

	@Column(name = "workExpDurationMonth", nullable = false)
	public int getWorkExpDurationMonth() {
		return this.workExpDurationMonth;
	}

	public void setWorkExpDurationMonth(int workExpDurationMonth) {
		this.workExpDurationMonth = workExpDurationMonth;
	}

	@Column(name = "workExpBelgium", nullable = true)
	public Boolean isWorkExpBelgium() {
		return this.workExpBelgium;
	}

	public void setWorkExpBelgium(Boolean workExpBelgium) {
		this.workExpBelgium = workExpBelgium;
	}

	@Column(name = "workSector", nullable = false, length = 100)
	public String getWorkSector() {
		return this.workSector;
	}

	public void setWorkSector(String workSector) {
		this.workSector = workSector;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workexperience", cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<WorkTask> getWorktasks() {
		return this.worktasks;
	}

	public void setWorktasks(Set<WorkTask> worktasks) {
		this.worktasks = worktasks;
	}

	@Override
	public String toString() {
		return this.workExpName;
	}

}
